services:
  - type: web
    name: calendar-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
    autoDeploy: true 