services:
  - type: web
    name: calendar-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/run_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
    autoDeploy: true 